name: Environment Setup

description: Initialize Environment with Composite Actions

runs:
  using: composite
  steps:
    - name: setup-python action
      uses: actions/setup-python@v3
      shell: bash
      with:
        python-version: '3.8.10'
        # cache: 'pip'
    # Runs a set of commands using the runners shell
    - name: install requirements.txt
      shell: bash
      run: pip install -r requirements.txt