# This is a basic workflow to help you get started with Actions

name: build environment

# Controls when the workflow will run
on:
  # Allows workflow to be re-used
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: ./environment_setup_action
      # - uses: actions/setup-python@v3
      #   with:
      #     python-version: '3.8.10'
      #     # cache: 'pip'

      # # Runs a set of commands using the runners shell
      # - name: install requirements.txt
      #   run: pip install -r requirements.txt

