# This is a basic workflow to help you get started with Actions

name: Deploy_Development

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ development ]
  
  # should only be able to open PR from
  # - feature/* -> development
  # - release/* -> development
  # - hotfix/* -> development
  pull_request:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # call "build" workflow which validates all environment setup requirements
  call-build:
    uses: ./.github/workflows/build.yaml

  validate:
    # indicating dependency, will not run till call-build job succeeds
    needs: call-build

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # indicates Github environment specification
    environment: development

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # runs composite action defined in ./environment_setup_action/action.yaml
      - uses: ./environment_setup_action
      # environment-agnostic validation
      - uses: ./standard_validation_action

    # ----------------------------------------------------------------------- #

      # run development-specific tests
      - name: development test
        run: python ./__test__/development_test.py
