# This is a basic workflow to help you get started with Actions

name: Deploy_Prod

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # call base workflow which validates all envirnoment build requirements
  call-build:
    uses: ./.github/workflows/build.yaml

  validate:
    # indicating dependency
    needs: call-build

    # ----------------------------------------------------------------------- #
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment: production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: ./.github/workflows/build.yaml
    # ----------------------------------------------------------------------- #

      # run a test
      - name: some test
        run: python ./__test__/some_test.py
